In [2]:
#TO USE datadotworld PACKAGE:
#1. create account at data.world, then run the next two lines:
#2. in terminal/powershell: pip install datadotworld[pandas]
#
#   IF THIS DOESN'T WORK BC YOU GET AN ERROR ABOUT "CCHARDET", RUN:
#    conda install -c conda-forge cchardet
#   THEN RERUN: pip install datadotworld[pandas] 
#
#3. in terminal/powershell: dw configure          
#3a. copy in API token from data.world (get from settings > advanced)

import datadotworld as dw
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

baby_names = dw.load_dataset('nkrishnaswami/us-ssa-baby-names-national')
baby_names = baby_names.dataframes['names_ranks_counts']

In [3]:
all_tables = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')


constitutents_tables = all_tables[0]
constitutents_tables

,Symbol,Security,SEC filings,GICS Sector,GICS Sub Industry,Headquarters Location,Date first added,CIK,Founded
0,MMM,3M Company,reports,Industrials,Industrial Conglomerates,"St. Paul, Minnesota",1976-08-09,66740,1902
1,ABT,Abbott Laboratories,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888
2,ABBV,AbbVie Inc.,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
3,ABMD,ABIOMED Inc,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981
4,ACN,Accenture plc,reports,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
5,ATVI,Activision Blizzard,reports,Communication Services,Interactive Home Entertainment,"Santa Monica, California",2015-08-31,718877,2008
6,ADBE,Adobe Inc.,reports,Information Technology,Application Software,"San Jose, California",1997-05-05,796343,1982
7,AMD,Advanced Micro Devices Inc,reports,Information Technology,Semiconductors,"Santa Clara, California",2017-03-20,2488,1969
8,AAP,Advance Auto Parts,reports,Consumer Discretionary,Automotive Retail,"Raleigh, North Carolina",2015-07-09,1158449,1932
9,AES,AES Corp,reports,Utilities,Independent Power Producers & Energy Traders,"Arlington, Virginia",1998-10-02,874761,1981
10,AFL,AFLAC Inc,reports,Financials,Life & Health Insurance,"Columbus, Georgia",1999-05-28,4977,1955
11,A,Agilent Technologies Inc,reports,Health Care,Health Care Equipment,"Santa Clara, California",2000-06-05,1090872,1999
12,APD,Air Products & Chemicals Inc,reports,Materials,Industrial Gases,"Allentown, Pennsylvania",1985-04-30,2969,1940
13,AKAM,Akamai Technologies Inc,reports,Information Technology,Internet Services & Infrastructure,"Cambridge, Massachusetts",2007-07-12,1086222,1998
14,ALK,Alaska Air Group Inc,reports,Industrials,Airlines,"Seattle, Washington",2016-05-13,766421,1985
15,ALB,Albemarle Corp,reports,Materials,Specialty Chemicals,"Charlotte, North Carolina",2016-07-01,915913,1994
16,ARE,Alexandria Real Estate Equities,reports,Real Estate,Office REITs,"Pasadena, California",2017-03-20,1035443,1994
17,ALXN,Alexion Pharmaceuticals,reports,Health Care,Biotechnology,"Boston, Massachusetts",2012-05-25,899866,1992
18,ALGN,Align Technology,reports,Health Care,Health Care Supplies,"San Jose, California",2017-06-19,1097149,1997
19,ALLE,Allegion,reports,Industrials,Building Products,"Dublin, Ireland",2013-12-02,1579241,1908
20,ADS,Alliance Data Systems,reports,Information Technology,Data Processing & Outsourced Services,"Plano, Texas",2013-12-23,1101215,1996
21,LNT,Alliant Energy Corp,reports,Utilities,Electric Utilities,"Madison, Wisconsin",2016-07-01,352541,1917
22,ALL,Allstate Corp,reports,Financials,Property & Casualty Insurance,"Northfield Township, Illinois",1995-07-13,899051,1931
23,GOOGL,Alphabet Inc. (Class A),reports,Communication Services,Interactive Media & Services,"Mountain View, California",2014-04-03,1652044,1998
24,GOOG,Alphabet Inc. (Class C),reports,Communication Services,Interactive Media & Services,"Mountain View, California",2006-04-03,1652044,1998
25,MO,Altria Group Inc,reports,Consumer Staples,Tobacco,"Richmond, Virginia",NaN,764180,1985
26,AMZN,Amazon.com Inc.,reports,Consumer Discretionary,Internet & Direct Marketing Retail,"Seattle, Washington",2005-11-18,1018724,1994
27,AMCR,Amcor plc,reports,Materials,Paper Packaging,"Warmley, Bristol, United Kingdom",2019-06-07,1748790,2019 (1860)
28,AEE,Ameren Corp,reports,Utilities,Multi-Utilities,"St. Louis, Missouri",1991-09-19,1002910,1902
29,AAL,American Airlines Group,reports,Industrials,Airlines,"Fort Worth, Texas",2015-03-23,6201,1934
...,...,...,...,...,...,...,...,...,...
475,VNO,Vornado Realty Trust,reports,Real Estate,Office REITs,"New York, New York",NaN,899689,1982
476,VMC,Vulcan Materials,reports,Materials,Construction Materials,"Birmingham, Alabama",1999-06-30,1396009,NaN
477,WRB,W. R. Berkley Corporation,reports,Financials,Property & Casualty Insurance,"Greenwich, Connecticut",2019-12-05,11544,1967
478,WAB,Wabtec Corporation,reports,Industrials,Construction Machinery & Heavy Trucks,"Wilmerding, Pennsylvania",2019-02-27,943452,1999 (1869)
479,WMT,Walmart,reports,Consumer Staples,Hypermarkets & Super Centers,"Bentonville, Arkansas",1982-08-31,104169,NaN
480,WBA,Walgreens Boots Alliance,reports,Consumer Staples,Drug Retail,"Deerfield, Illinois",1979-12-31,1618921,2014
481,DIS,The Walt Disney Company,reports,Communication Services,Movies & Entertainment,"Burbank, California",1976-06-30,1001039,NaN
482,WM,Waste Management Inc.,reports,Industrials,Environmental & Facilities Services,"Houston, Texas",NaN,823768,1968
483,WAT,Waters Corporation,reports,Health Care,Health Care Distributors,"Milford, Massachusetts",NaN,1000697,1958
484,WEC,WEC Energy Group,reports,Utilities,Electric Utilities,"Milwaukee, Wisconsin",2008-10-31,783325,NaN
485,WFC,Wells Fargo,reports,Financials,Diversified Banks,"San Francisco, California",1976-06-30,72971,NaN
486,WELL,Welltower Inc.,reports,Real Estate,Health Care REITs,"Toledo, Ohio",2009-01-30,766704,NaN
487,WST,West Pharmaceutical Services,reports,Health Care,Health Care Supplies,"Exton, Pennsylvania",2020-05-22,105770,NaN
488,WDC,Western Digital,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Irvine, California",2009-07-01,106040,NaN
489,WU,Western Union Co,reports,Information Technology,Data Processing & Outsourced Services,"Englewood, Colorado",NaN,1365135,1851
490,WRK,WestRock,reports,Materials,Paper Packaging,"Richmond, Virginia",NaN,1636023,2015
491,WY,Weyerhaeuser,reports,Real Estate,Specialized REITs,"Federal Way, Washington",NaN,106535,1900
492,WHR,Whirlpool Corp.,reports,Consumer Discretionary,Household Appliances,"Benton Harbor, Michigan",NaN,106640,1911
493,WMB,Williams Cos.,reports,Energy,Oil & Gas Storage & Transportation,"Tulsa, Oklahoma",1975-03-31,107263,NaN
494,WLTW,Willis Towers Watson,reports,Financials,Insurance Brokers,"London, United Kingdom",2016-01-05,1140536,NaN
495,WYNN,Wynn Resorts Ltd,reports,Consumer Discretionary,Casinos & Gaming,"Paradise, Nevada",2008-11-14,1174922,NaN
496,XEL,Xcel Energy Inc,reports,Utilities,Multi-Utilities,"Minneapolis, Minnesota",NaN,72903,1909
497,XRX,Xerox,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Norwalk, Connecticut",NaN,108772,1906
498,XLNX,Xilinx,reports,Information Technology,Semiconductors,"San Jose, California",1999-11-08,743988,NaN
499,XYL,Xylem Inc.,reports,Industrials,Industrial Machinery,"White Plains, New York",2011-11-01,1524472,2011
500,YUM,Yum! Brands Inc,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,NaN
501,ZBRA,Zebra Technologies,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
502,ZBH,Zimmer Biomet Holdings,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,NaN
503,ZION,Zions Bancorp,reports,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,NaN
504,ZTS,Zoetis,reports,Health Care,Pharmaceuticals,"Florham Park, New Jersey",2013-06-21,1555280,1952

In [4]:
import glob

csvfiles = glob.glob("C:/Users/ericm/OneDrive/Documents/GitHub/My Falling Knives/falling-knives-capstone/StockData/*.csv")

dfs = [pd.read_csv(f, header=None, error_bad_lines=False,sep=";") for f in csvfiles]

salesdata = pd.concat(dfs,ignore_index=True)

salesdata

b'Skipping line 282: expected 1 fields, saw 2\n'

                                                         0
0                Date,High,Low,Open,Close,Volume,Adj Close
1        2005-09-27,21.399999618530273,19.1000003814697...
2        2005-09-28,20.530000686645508,19.2000007629394...
3        2005-09-29,20.579999923706055,20.1000003814697...
4        2005-09-30,21.049999237060547,20.1800003051757...
5        2005-10-03,21.75,20.899999618530273,20.8999996...
6        2005-10-04,22.5,21.440000534057617,21.44000053...
7        2005-10-05,22.309999465942383,21.75,22.1000003...
8        2005-10-06,23.0,22.399999618530273,22.60000038...
9        2005-10-07,22.600000381469727,21.7999992370605...
10       2005-10-10,22.290000915527344,22.1000003814697...
11       2005-10-11,22.299999237060547,21.7999992370605...
12       2005-10-12,22.049999237060547,21.6399993896484...
13       2005-10-13,21.799999237060547,21.3999996185302...
14       2005-10-14,22.399999618530273,21.8500003814697...
15       2005-10-17,22.219999313354492,21.8500003814697...
16       2005-10-18,22.299999237060547,21.3500003814697...
17       2005-10-19,21.600000381469727,20.8500003814697...
18       2005-10-20,21.479999542236328,20.8500003814697...
19       2005-10-21,22.420000076293945,21.0100002288818...
20       2005-10-24,22.360000610351562,21.9500007629394...
21       2005-10-25,22.540000915527344,21.7000007629394...
22       2005-10-26,22.450000762939453,21.9899997711181...
23       2005-10-27,22.559999465942383,22.2000007629394...
24       2005-10-28,23.899999618530273,22.3700008392334...
25       2005-10-31,25.350000381469727,24.0,24.0,24.680...
26       2005-11-01,25.079999923706055,24.6900005340576...
27       2005-11-02,28.100000381469727,25.2000007629394...
28       2005-11-03,28.100000381469727,27.6000003814697...
29       2005-11-04,29.0,27.770000457763672,27.79999923...
...                                                    ...
3854765  2020-01-10,136.0,134.77000427246094,135.300003...
3854766  2020-01-13,136.75,135.4600067138672,136.070007...
3854767  2020-01-14,137.27999877929688,135.520004272460...
3854768  2020-01-15,139.0,137.33999633789062,137.410003...
3854769  2020-01-16,139.39999389648438,138.020004272460...
3854770  2020-01-17,140.39999389648438,138.860000610351...
3854771  2020-01-21,142.52000427246094,138.970001220703...
3854772  2020-01-22,143.3300018310547,141.2100067138672...
3854773  2020-01-23,141.77000427246094,137.520004272460...
3854774  2020-01-24,139.6199951171875,136.1499938964843...
3854775  2020-01-27,136.44000244140625,134.029998779296...
3854776  2020-01-28,138.9199981689453,135.4900054931640...
3854777  2020-01-29,139.97000122070312,138.440002441406...
3854778  2020-01-30,138.3300018310547,136.0599975585937...
3854779  2020-01-31,137.97000122070312,134.0,137.600006...
3854780  2020-02-03,137.47000122070312,134.199996948242...
3854781  2020-02-04,139.44000244140625,136.690002441406...
3854782  2020-02-05,140.3000030517578,137.5399932861328...
3854783  2020-02-06,139.10000610351562,136.869995117187...
3854784  2020-02-07,139.16000366210938,138.029998779296...
3854785  2020-02-10,142.74000549316406,138.350006103515...
3854786  2020-02-11,144.35000610351562,142.649993896484...
3854787  2020-02-12,144.4600067138672,142.4299926757812...
3854788  2020-02-13,146.25999450683594,141.25,141.92999...
3854789  2020-02-14,145.39999389648438,143.119995117187...
3854790  2020-02-18,144.1300048828125,142.6100006103515...
3854791  2020-02-19,145.61000061035156,142.809997558593...
3854792  2020-02-20,144.08999633789062,141.240005493164...
3854793  2020-02-21,143.0,141.5,142.92999267578125,142....
3854794  2020-02-24,140.81790161132812,137.535003662109...

[3854795 rows x 1 columns]